// Generated by Scripts/gen-companion-atlas.js — do not edit by hand.
import CoreGraphics

/// The Companion's sprite sheet: one decoded image, `columns` × `rows` cells of `frameWidth` each.
/// A frame is a rectangle into that one image, never an image of its own — which is why a pose
/// change costs a CGRect and not a decode.
enum CompanionAtlas {
    static let frameWidth: CGFloat = 48
    static let frameHeight: CGFloat = 48
    static let columns = 5
    static let rows = 6

    static var imageSize: CGSize { CGSize(width: frameWidth * CGFloat(columns), height: frameHeight * CGFloat(rows)) }

    enum Row: Int, CaseIterable, Sendable {
        case idle = 0
        case walkLeft = 1
        case walkRight = 2
        case reaction = 3
        case daze = 4
        case acrobatics = 5

        /// How many of the row's cells carry a frame. The rest are padding, and asking for one is
        /// a caller bug rather than something to clamp here.
        var frameCount: Int {
            switch self {
            case .idle: return 3
            case .walkLeft, .walkRight: return 4
            case .reaction: return 5
            case .daze: return 4
            case .acrobatics: return 4
            }
        }
    }

    /// The reaction row's poses, by the column each one starts at. The walk rows have no names for
    /// their cells: they are one cycle, and the cell *is* the position in it.
    enum Reaction: Int, CaseIterable, Sendable {
        case glance = 0
        case wave = 2
        case chat = 4

        var frameCount: Int { self == .chat ? 1 : 2 }
    }
}
