import Foundation

/// The UserDefaults keys `AppSettings` owns; `CaseIterable` so the backup harness enumerates them.
enum AppSettingsKey: String, CaseIterable {
    // Every raw value is spelled out so renaming a case can never rename a persisted key.
    case clipboardEnabled = "clipboardEnabled"
    case clipboardRetention = "clipboardRetentionDays"
    case clipboardDefaultAction = "clipboardDefaultAction"
    case clipboardDisabledApps = "clipboardDisabledApps"
    case hyperKey = "hyperKeyPhysicalKey"
    case hyperKeyIncludesShift = "hyperKeyIncludesShift"
    case hyperKeyQuickPress = "hyperKeyQuickPress"
    case popToRootTimeout = "popToRootTimeout"
    case escapeKeyBehavior = "escapeKeyBehavior"
    case appearance = "appearance"
    case interfaceSize = "interfaceSize"
    case paletteTransparency = "paletteTransparency"
    case compactMode = "compactMode"
    case showFavoritesInCompactMode = "showFavoritesInCompactMode"
    case searchScopes = "launcherSearchScopes"
    case launcherShowsSuggestions = "launcherShowsSuggestions"
    case rootSearchSensitivity = "rootSearchSensitivity"
    case openOnCursorScreen = "openOnCursorScreen"
    case autoSwitchInputSource = "autoSwitchInputSource"
    case paletteDraggable = "paletteDraggable"
    case palettePosition = "palettePosition"
    case fileSearchEnabled = "fileSearchEnabled"
    case fileSearchScopes = "fileSearchScopes"
    case fileSearchIgnorePatterns = "fileSearchIgnorePatterns"
    case notesEnabled = "notesEnabled"
    case notesRendersMarkdown = "notesRendersMarkdown"
    case notesShowsFormattingBar = "notesShowsFormattingBar"
    case notesDirectoryPath = "notesDirectoryPath"
    case navigationEnabled = "navigationEnabled"
    case menuSearchDisabledApps = "menuSearchDisabledApps"
    case menuSearchShowsAppleMenu = "menuSearchShowsAppleMenu"
    case windowGap = "windowManagementGap"
    case deloresCompanionMode = "deloresCompanionMode"
    // Kept only so an older install can be read once when the mode is initialized.
    case deloresCompanionEnabled = "deloresCompanionEnabled"
    case deloresCompanionSize = "deloresCompanionSize"
    case deloresCompanionKind = "deloresCompanionKind"
    case deloresWindowSnappingEnabled = "deloresWindowSnappingEnabled"
    case deloresSplitDividerEnabled = "deloresSplitDividerEnabled"
    case quicklinksEnabled = "quicklinksEnabled"
    case quicklinksShowInLauncher = "quicklinksShowInLauncher"
    case quicklinkOpensNewWindow = "quicklinkOpensNewWindow"
    case quicklinkSelectionFallback = "quicklinkSelectionFallback"
    case quicklinkConfirmsBeforeDelete = "quicklinkConfirmsBeforeDelete"
    case appleShortcutsEnabled = "appleShortcutsEnabled"
    case aiEnabled = "aiEnabled"
    case aiInstalledProviders = "aiInstalledProviders"
    case aiConnections = "aiConnections"
    case aiDefaultModel = "aiDefaultModel"
    case aiWebSearch = "aiWebSearch"
    case aiSystemPrompt = "aiSystemPrompt"
    case aiSystemPromptEnabled = "aiSystemPromptEnabled"
    case aiRetention = "aiRetentionDays"
    case aiOpensTo = "aiOpensTo"
    case aiNewChatAfter = "aiNewChatAfterMinutes"
    case mcpEnabled = "mcpEnabled"
    case mcpServers = "mcpServers"
    case quickActionsEnabled = "quickActionsEnabled"
    case quickActionModel = "quickActionModel"
    case quickActionModelOverrides = "quickActionModelOverrides"
    case quickActionPreviews = "quickActionPreviews"
    case quickActionInstructions = "quickActionInstructions"
    case quickActionLanguage = "quickActionLanguage"
}
